### ISSUE TITLE
AttributeError: module 'conda_build.metadata' has no attribute 'cc'

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/conda-smithy-feedstock#34]
My *assumption* is that this break is caused by using the just-released latest-and-greatest `conda-build` (`1.21.12`, with `python==3.5`)

Running it on a fork of the `requests-futures-feedstock`, I get:
```bash
$ conda smithy regenerate
Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 185, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 361, in main
    render_run_docker_build(env, config, forge_dir)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 24, in render_run_docker_build
    with fudge_subdir('linux-64'):
  File "/opt/anaconda3/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 103, in fudge_subdir
    orig = conda_build.metadata.cc.subdir
AttributeError: module 'conda_build.metadata' has no attribute 'cc'
```

**Comment by jakirkham** [comment]
Thanks for raising this issue, @pmlandwehr. Can confirm seeing this as well myself. See issue ( https://github.com/conda-forge/status/issues/3 ) for a description of another occurrence of this issue, build logs showing the problem, and what was done to fix it. Have found that downgrading to `conda-build` version `1.21.11` seems to be a sufficient workaround for the meantime.

FYI this repo is the feedstock used to generate `conda-smithy` releases. As this isn't an issue generating the package itself, but an issue with `conda-smithy` (I think), I'm going to move this over to the [`conda-smithy` repo]( https://github.com/conda-forge/conda-smithy ). Thanks again for bring this to our attention.

**Comment by jakirkham** [comment]
Issue moved to [conda-forge/conda-smithy #260](https://github.com/conda-forge/conda-smithy/issues/260) via [**ZenHub**](https://www.zenhub.com/)
